# Generated by Django 6.0.3 on 2026-06-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('criador', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField()),
                ('temporadas', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
